# artillery.yml
config:
  target: "http://localhost:8080"
  phases:
    - duration: 20
      arrivalRate: 10
  plugins:
    metrics-by-endpoint: {}

scenarios:
  - name: "Proceso general de registro de usuario"
    flow:
      - log: "creando usuario"
      - get:
          url: "/test-user"
          capture:
            - json: "$.first_name"
              as: "first_name"
            - json: "$.last_name"
              as: "last_name"
            - json: "$.email"
              as: "email"
            - json: "$.password"
              as: "password"

      - log: "Registramos el usuario"
      - post:
          url: "/register"
          json:
            first_name: "{{ first_name }}"
            last_name: "{{ last_name }}"
            email: "{{ email }}"
            password: "{{ password }}"

      - think: 2

      - log: "logiando usuario"
      - post:
          url: "/login"
          json:
            email: "{{ email }}"
            password: "{{ password }}"
      - log: "loginexitoso"